name: CI

on:
  pull_request:

jobs:

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/checkout@v4.2.2
    - name: Run checks
      run: nix flake check -L

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/checkout@v4.2.2
    - name: Run build
      run: nix-build --no-out-link .
    - name: Create artifact
      run: cp $(nix-build --no-out-link . -A deb) nix-multi-user.deb
    - uses: actions/upload-artifact@v4
      with:
        name: nix-multi-user.deb
        path: nix-multi-user.deb
        retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: nix-multi-user.deb
        path: nix-multi-user.deb
    - name: Install Nix
      run: sudo dpkg -i nix-multi-user.deb/nix-multi-user.deb
    - name: Run nix-shell
      run: bash -l -c "nix-shell -p hello --run hello"

  collect:
    runs-on: ubuntu-latest
    needs:
      - checks
      - build
      - test
    steps:
      - run: true
