name: CI

on:
  pull_request:

jobs:

  nixpkgs-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/checkout@v4.1.1
    - name: Check format
      run: nix-shell --run "nixpkgs-fmt --check ."

  black:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/checkout@v4.1.1
    - name: Check format
      run: nix-shell --run "black --check ."

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/checkout@v4.1.1
    - name: Check format
      run: nix-shell --run "git ls-files | grep -P '\.py$' | xargs mypy --strict"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/checkout@v4.1.1
    - name: Run build
      run: nix-build --no-out-link .
    - name: Create artifact
      run: cp $(nix-build --no-out-link . -A deb) nix-multi-user.deb
    - uses: actions/upload-artifact@v3
      with:
        name: nix-multi-user.deb
        path: nix-multi-user.deb
        retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nix-multi-user.deb
        path: nix-multi-user.deb
    - name: Install Nix
      run: sudo dpkg -i nix-multi-user.deb/nix-multi-user.deb
    - name: Run nix-shell
      run: bash -l -c "nix-shell -p hello --run hello"
