name: Github Pages

on:
  push:
    branches:
      - master

jobs:

  pages:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/checkout@v4.1.1
    - name: Run build
      run: nix-build .github/pages.nix
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./result
        force_orphan: true
